# Generated by Django 3.1.3 on 2020-11-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201124_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_img',
            new_name='image',
        ),
    ]
