# Generated by Django 3.1.3 on 2020-11-30 12:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201130_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=81, populate_from='slugify', unique=True),
        ),
    ]
